name: Setup Gradle Environment
description: Execute all steps to have a complete Gradle Environment, including Java installation, Gradle Setup and permission handling
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execution permission to Gradle Wrapper
      run: chmod +x ./gradlew
      shell: bash